project:
  type: website
  output-dir: docs

website: 
  title: "Calculus II <br>MTH202 :: Fall 2026"

  page-navigation: true

  navbar:
    search: true

  sidebar:
    title: false
    pinned: true
    align: left

    style: docked
    search: false
    collapse-level: 2

    contents:
      - href: index.qmd
        text: Welcome
      - href: general.qmd
        text: General Info
      - href: support.qmd
      - href: content.qmd
        text: Course Content
      - href: structure.qmd
      - href: grades.qmd
      - href: UPElements.qmd
        text: University Policies
      - section: "Slides"
        contents:
          - href: slides/Week_01/01-introductions.qmd
            text: "Introductions"
            target: _blank
          
format:
  html:
    theme: [litera, mth202.scss]
    toc: true
    number-sections: false
    highlight-style: monokai
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    margin-left: 30mm
    margin-right: 30mm
    toc: false
    number-sections: true
    colorlinks: true
    pdf-engine: pdflatex
    include-in-header:  
        - text: |
            \usepackage{enumitem}

   
      
editor: visual

  