---
title: "Course Content"

format:
  html: 
    toc: true
    toc-expand: 1
    toc-title: "On this page"
  
  pdf: 
    toc: false
    number-sections: true
    colorlinks: true 
---

Broadly speaking, this course covers the foundational topics of **integral calculus** which includes methods of evaluating integrals as well as their use in the context of a variety of applications. We will also cover Taylor series, an important tool as you build on your understanding of calculus in later courses.  Additional topics may be covered as time allows.

## Learning Targets

The bulk of the course content is represented by the following specific topics which we will call **Learning Targets**. Your goal over the course of the semester is to develop your understanding of these topics and to demonstrate that understanding via various assessment tasks -- primarily our weekly check-ins. I've organized these topics to generally align with our textbook.

### Evaluating Integrals

**I1.** I can evaluate integrals using substitution methods.

**I2.** I can evaluate integrals using integration by parts.

**I3.** I can evaluate integrals using additional methods such as partial fractions, trig substitution, or tables.

**I4.** I can evaluate integrals when the appropriate method is not prescribed and/or when multiple methods are needed.

**I5.** I can determine whether improper integrals converge and evaluate them if they do.

### Applications of Integrals

**A1.** I can use definite integrals to find the area of a region enclosed by multiple curves.

**A2.** I can use definite integrals to find the arc length of a curve.

**A3.** I can use definite integrals to find the volume of a solid of revolution.

**A4.** I can use definite integrals to find the mass and center of mass of an object.

**A5.** I can use definite integrals to represent key quantities in physical applications such as work or pressure.

### Differential Equations

**D1.** I can determine whether a function is a solution to a differential equation and explain why the function is or is not a solution.

### Taylor Polynomials and Series

**T1.** I can find the Taylor polynomial for a given function with a specified degree and center.

**T2.** I can identify geometric series a find their sum if they converge.

**T3.** I can use the Taylor series of one or more familiar functions to find the Taylor series for a related function.

### Mathematical Practice

In addition to specific Calculus topics, we will also develop more general aspects of your mathematical practice including

-   Ability to communicate mathematical thinking effectively, including correct use of vocabulary, notation, and mathematial representations.

-   Ability to solve complex and unfamiliar problems.

-   Ability to use technology effectively.
