---
title: "f25_schedule"
format: html
---

Week One
Monday:   Introductions.  If you haven't already filled out the short survey I emailed last week, please do so before Wednesday (shout out to those of you that have done that already!). We also spent some time with some Calc I review/warm up problems.  

Today's worksheet
For Wednesday, please take a look at the syllabus (link at the top of this page) and come to class with your questions.

Wednesday: 
Summary of review questions
Review solutions
If you would like more practice with simple integrals like the ones on this review worksheet, do the Integration Review activity on WeBWorK (link above)
For Thursday -- Do Preview Activity 5.3.1 before class
Remember -- different room!

Thursday:
We discussed preview activity in groups and I answered some questions that came up.  We moved on to Activity 5.3.2 -- if you didn't get through that in class, try to finish those problems before tomorrow.  We will start with section 5.3.3 on Friday. 
Friday:

Finish section 5.3.  Activity 5.3.3 in class.  We probably wont get to Activity 5.3.4 in class, so please take a look at that section on your own -- we will be moving on to section 5.4 on Monday.
Homework:  do #4, 5, 7, 10, 11, 13 in section 5.3
HW Report due Wednesday in class.  Update: hw due Thursday
Preview Activity:  do preview activity 5.4.1 before class on Monday.  Come to class prepared to discuss.
Assignment icon
Preview Activity 5.3.1Assignment
Write-up this activity from the textbook and bring it to class tomorrow (8/28).
 Not available unless: You belong to MTH-202A - fa25 - Calculus II course
Assignment icon
Preview Activity 5.3.1Assignment
Write-up this activity from the textbook and bring it to class tomorrow (8/28).
 Not available unless: You belong to MTH-202B - fa25 - Calculus II course
Assignment icon
Homework #1Assignment
Opened: Friday, August 29, 2025, 12:00 AM
Due: Thursday, September 4, 2025, 5:00 PM
September 1 - September 7
Week Two
Monday:   Today we started section 5.4 on Integration by Parts and got through Activity 5.4.2.  We will continue with section 5.4.3 on Thursday.

on Thursday we will have our first check-in covering mostly u-substitution so make sure your questions get answered before then.
Wednesday's class is cancelled for both sections.  The homework that was due on Wednesday is now due on Thursday.

Wednesday:  class cancelled. 

Thursday: 
we spent a little time in groups going over homework questions; I also had everyone fill out this homework report and attach that to your HW.  In general, I'll be asking you to complete a similar short report every week.
Check-In #1
Tomorrow, we will finish up Section 5.4 on Integration by Parts. 
Friday:
Finish section 5.4 -- work on Activity 5.4.3 and go additional examples from section 5.4.  For extra practice, I suggest Activity 5.4.4.
For Monday: do Preview Activity 5.5.1 before class
Homework #2 due next Wednesday:  do problems #1, 3, 4, 11, 13 from section 5.4.8
Assignment icon
AEP #1Assignment
Opened: Wednesday, September 3, 2025, 12:00 AM
Due: Friday, September 12, 2025, 2:00 PM
Assignment icon
Check-in #1 (online version)Assignment
Opened: Thursday, September 4, 2025, 12:00 AM
Due: Friday, September 5, 2025, 11:59 PM
 Not available unless: Your Email address is kenth28@up.edu
Assignment icon
Homework #2Assignment
Opened: Friday, September 5, 2025, 12:00 AM
Due: Wednesday, September 10, 2025, 5:00 PM
September 8 - September 14
Week Three
Monday:   We began section 5.5 today, focusing our discussion on partial fractions and Activity 5.5.2.  On Wednesday, we will wrap that up and move on to sections 5.5.3 and 5.5.4.

Wednesday:  Finished section 5.5, focusing our discussion on using tables like the one in Appendix A of our textbook.  We did Activity 5.5.3.  

For our check-in tomorrow, be prepared to do integration by parts integrals as well as a partial fraction integral like the ones on Monday's activity.
We will start section 6.1 on Friday (note we are skipping section 5.6), so please make sure you complete Preview Activity 6.1.1 before then.
Thursday:  I briefly went over the trig substitution technique that produces the integration rules like the ones on the table we discussed on Wednesday.  We also did our 2nd check-in.

Friday:  start section 6.1 with Preview Activity 6.1.1, followed by Activity 6.1.2.  Please fill out the short group work survey before Sunday evening.

Feedback icon
Group Work SurveyFeedback
Opened: Friday, September 12, 2025, 9:18 AM
Closed: Sunday, September 14, 2025, 5:00 PM
On Monday I want to shuffle the groups so that everyone has a chance to work with other people.  But I also want to take your preferences regarding group work into account, so I'm asking you to please fill out this short survey before Monday.

Assignment icon
Homework #3Assignment
Opened: Friday, September 12, 2025, 12:00 AM
Due: Wednesday, September 17, 2025, 5:00 PM
Assignment icon
Check-In #2Assignment
Opened: Friday, September 12, 2025, 12:00 AM
Due: Wednesday, September 17, 2025, 5:00 PM
 Not available unless: Your Email address is kenth28@up.edu
September 15 - September 21
Week Four
Monday:   Continue with section 6.1.3.  We began activity 6.1.3 but didn't get too far, so we'll continue with this on Wednesday.  

Wednesday:  answered leftover questions about activity 6.1.3 then moved on to section/activity 6.1.4.  We pointed out that the integrals that come out of the arc length formula are almost always integrals that we need to use our table of integrals for.

Note: there are now WebWork problem sets for area between curves as well as arc length.  The arc length assignment includes one question dealing with surface area -- you can ignore that!

Thursday: 
Masyu Instructions
Check-in #3
Friday: we started section 6.2 on volumes of revolution, focusing on solid shapes obtained by rotating a region around the x-axis.  Activity 6.2.2.
Assignment icon
AEP #2Assignment
Opened: Monday, September 15, 2025, 12:00 AM
Due: Friday, September 26, 2025, 5:00 PM
Assignment icon
Homework #4Assignment
Opened: Wednesday, September 17, 2025, 12:00 AM
Due: Monday, September 22, 2025, 5:00 PM
Do problems #2, 3, 4, 8, 11 from Section 6.1.6.  Remember to include a Homework Report (same as previous assignments).

September 22 - September 28
Week Five
Monday:   Continue with section 6.2, focusing on regions revolved around the y-axis and then other vertical or horizontal lines.  Activities 6.2.3 and 6.2.4. 

For Wednesday, please complete Preview Activity 6.3 prior to class.
Wednesday:  Started Section 6.3 and worked up through Activity 6.3.2

Thursday:  I briefly went over section 6.3.3 on Weighted Averages and introduced Center of Mass.  We also did Check-in #4.

Friday:  we did Activity 6.3.4.
For Monday, please complete Preview Activity 6.4 prior to class.  I will be collecting a write-up of this activity, so please come prepared to hand something in.

Assignment icon
Homework #5Assignment
Opened: Monday, September 22, 2025, 12:00 AM
Due: Friday, September 26, 2025, 5:00 PM
Do problems #1, 3, 4, 8 from section 6.2.6.  In addition, do this problem:

Find the volume of a sphere of radius R that has had a hole of radius r (r<R) drilled through the center.
Write up problem #8 and the additional problem, plus the usual homework report.  Due Friday, Sept. 26th.

September 29 - October 5
Week Six
Monday:   Today we began section 6.4, focusing on setting up integrals to calculate work.  In our groups, we did Activity 6.4.2 and at the end of class, I briefly went over the setup for Example 6.4.3 from the book.  Note that the way I set it up is a bit different from the setup in the textbook.  On Wednesday, we'll continue with this example and then move on to Activity 6.4.3.

Wednesday:  We worked on Activity 6.4.3.
Tomorrow's check-in will focus on volumes of revolution (section 6.2) as well as using integrals to calculate mass and center of mass (section 6.3).
No class this Friday -- I will post an activity + assignment for you to do instead.

Thursday:  I went over Example 6.4.5 and then we did our check-in.

Friday:  no class today!  Instead, please complete the assignment below by Sunday 5pm.
Assignment icon
Why math?Assignment
Opened: Thursday, October 2, 2025, 12:00 AM
Due: Sunday, October 5, 2025, 5:00 PM
Think about the following questions and write a few sentences in response. 
What is mathematics? How would you describe it to a friend, in a sentence or two?
What do you feel is the purpose of learning mathematics, for yourself or others?​

Watch the following video (it's approx 45 minutes).  Note that although this particular talk is aimed at an audience of teachers, and some of his language reflects that, it's essentially the same talk he gives to more general audiences.  https://www.youtube.com/watch?v=mhrunq8j3wk&t=0s

Finally, revisit your answers to the above questions and describe how your responses might have changed after watching the video. 

Assignment icon
Homework #6Assignment
Opened: Monday, September 29, 2025, 12:00 AM
Due: Monday, October 6, 2025, 5:00 PM
Do problems  #2, 5 from section 6.3.6
Do problems #1, 3, 7 from section 6.4.6
Hand in a write up of problems 5 and 7 plus the usual homework report. 
Due Monday, Oct. 6
Assignment icon
AEP #3Assignment
Opened: Monday, September 29, 2025, 12:00 AM
Due: Friday, October 10, 2025, 4:00 PM
October 6 - October 12
Week Seven
Monday:   We started Section 6.5 on Improper Integrals and worked up through Activity 6.5.3  

Wednesday:  Finished Section 6.5, covering section 6.5.4. 
I handed out individual summaries of what proficiencies I have recorded for you - so if you weren't in class today, you can stop by my office to pick that up.  I will also have them tomorrow.
Thursday:  mid-semester check-in

Friday:  wrap up Section 6.5 with a discussion of determining whether an improper integral converges or not by comparing it with another integral that we know about.  See homework problem #9.
We also filled out a mid-semester survey -- if you didn't get a chance to complete it in class, please submit it on Moodle.  
After break I will shuffle the groups again, so please also fill out the short group-work survey below.
Assignment icon
Mid-Semester SurveyAssignment
Opened: Friday, October 10, 2025, 12:00 AM
Due: Friday, October 10, 2025, 5:00 PM
If you did not complete this in class, please submit your responses within the next couple of days.

Feedback icon
Group Work Survey #2Feedback
Opened: Friday, October 10, 2025, 10:52 AM
Closed: Sunday, October 19, 2025, 5:00 PM
After break we will shuffle groups again.  Your responses to this survey will help ensure that groups are working well for everyone.

Assignment icon
Homework #7Assignment
Opened: Thursday, October 9, 2025, 12:00 AM
Due: Wednesday, October 22, 2025, 5:00 PM
Do problems #3, 5, 8, 9, 10, 11 from Section 6.5.6.  Hand in a homework report along with a write-up of #10 and #11.  Note that for #11, you may be able to determine if the integrals in question converge or diverge without actually evaluating them!

October 13 - October 19
Fall Break
October 20 - October 26
Assignment icon
Preview Activity 7.1.1Assignment
Opened: Thursday, October 16, 2025, 12:00 AM
Due: Monday, October 20, 2025, 8:00 AM
Week Eight
Monday:   We started Section 7.1.  After discussing the Preview Activity in our groups, we thought about the questions

What is a differential equation?
What is a solution to a differential equation?
We also started Activity 7.1.2, but didn't get very far - we'll continue with that on Wednesday.

Wednesday:  Activity 7.1.2 and 7.1.4.  Webwork for this section is available (it's called Intro DE - but please note that there a a couple of problems there that we don't know how to do.  Feel free to ignore any problem that asks you to solve a DE.

Thursday:  We reviewed the differential equation 𝑦′=𝑘𝑦
 and talked about what "initial value" means.  Also, Check-In #6.

Friday:  Activity 7.1.3.  This finishes section 7.1 - we'll begin section 7.2 on Monday.
Assignment icon
Preview Activity 7.2.1Assignment
Opened: Friday, October 24, 2025, 12:00 AM
Due: Monday, October 27, 2025, 8:00 AM
Complete this before Monday's class.

Assignment icon
Homework #8Assignment
Opened: Friday, October 24, 2025, 12:00 AM
Due: Wednesday, October 29, 2025, 5:00 PM
Do problems #2, 3, 4, 8, and 9 from section 7.1.6.  Write a short report telling me

Which problems were you able to complete.  What problems did you get stuck on (if any).
What questions came up for you while doing these problems?  What strategies did you use to help resolve your questions?
What questions do you have after doing this assignment?
Hand in this report and solutions to #8 and 9 only.  Due Wednesday 10/29.
October 27 - November 2
Week Nine
Monday:   Section 7.2 - focus on Activity 7.2.2.  Here's a link to a handy slope field app:  dfield

Wednesday:  we worked on Activity 7.2.3, which completes section 7.2.  

Thursday:  check-in on improper integrals and differential equations.

Friday:  Started section 8.1
Assignment icon
AEP #4Assignment
Opened: Monday, October 27, 2025, 12:00 AM
Due: Friday, November 14, 2025, 5:00 PM
Assignment icon
Preview Activity 8.1.1Assignment
Opened: Wednesday, October 29, 2025, 12:00 AM
Due: Friday, October 31, 2025, 8:00 AM
Please do this before class on Friday.  Here is a link to a Desmos graph with a table that you might find useful for this activity:  https://www.desmos.com/calculator/zkw9aqslex

Assignment icon
Homework #9Assignment
Opened: Friday, October 31, 2025, 12:00 AM
Due: Wednesday, November 5, 2025, 8:00 AM
Do problems #2, 7, 9 from section 7.2.5.  Hand in a homework report that includes your solution to #9 as well as responses to the prompts

Were you able to compete all the problems?
What questions came up for you while doing these problems?  What strategies did you use to answer your questions?
What questions do you still have have after completing this assignment?
Due Wednesday in class
November 3 - November 9
Week Ten
Monday:   Finished 8.1 and started section 8.2

Wednesday:  Finished section 8.2.  We did not get to Activity 8.2.4 but we'll move on to section 8.3 on Friday.

Thursday:  check-in on differential equations and Taylor Polynomials.

Friday:  Started section 8.3 - we got through Activity 8.3.2 and I went over the generalization shown in the shaded box containing equation 8.3.7.  On Monday, we'll continue with section 8.3.3.
Assignment icon
Homework #10Assignment
Opened: Friday, November 7, 2025, 12:00 AM
Due: Wednesday, November 12, 2025, 5:00 PM
Do problems #2, 4, 5, 7, 8 in Section 8.2.  Write a short homework report telling me

Which problems were you able to complete?  
What difficulties did you encounter in doing these problems?  What strategies were you able to use to help resolve your questions?
What questions do you have after doing this assignment?
Hand in this report a solutions to 7 & 8 by Wednesday, Nov. 12. 
November 10 - November 16
Week Eleven
Monday:   Continued with section 8.3.  We covered section 8.3.3 and started talking about 8.3.4 but didn't get very far - we'll review that section on Wednesday before moving on to 8.4.

Wednesday:  We began section 8.4, getting as far as stating the Ratio Test.  We did an example similar to Example 8.4.2 - but instead of looking at ln(1+x) centered at a=0, we looked at ln(x) centered at a=1.  Section A just got started with Activity 8.4.2 and we'll continue with that on Friday.  Section B will start start that activity on Friday.

Thursday: today's check-in focused on Geometric Series (T2) and Taylor polynomials (T1).

Friday:  We completed Activity 8.4.2.
Assignment icon
Homework #11Assignment
Opened: Friday, November 14, 2025, 12:00 AM
Due: Wednesday, November 19, 2025, 5:00 PM
Do problems #5, 6, 8 from section 8.3 and problems #5, 6, 7 from section 8.4.  Write a short homework report telling me

Which problems were you able to complete?  
What difficulties did you encounter in doing these problems?  What strategies were you able to use to help resolve your questions?
What questions do you have after doing this assignment?
Hand in this report and two of your solutions (your choice) by Wednesday, Nov. 19. 
November 17 - November 23
Week Twelve
Monday:   We began section 8.5 by summarizing the Taylor series that we know and doing an example of finding the Taylor series of a new function by manipulating something related -- I did Preview Activity 8.5.1 as an example and then y'all did Activity 8.5.2.

Wednesday:   We continued with section 8.5 by looking at integrating and differentiating series.  We did parts of Activity 8.5.3 and Activity 8.5.4.

Thursday:  today's check-in focused on geometric series (T2) and using known Taylor series to find new ones (T3).

Friday:  today we began section 8.6, looking at alternating series and error estimates.  I did Example 8.6.3 at the board and in our groups we began Activity 8.6.2 although most groups only got through the first problem.  We will continue this activity on Monday.
Assignment icon
AEP #5Assignment
Opened: Tuesday, November 18, 2025, 12:00 AM
Due: Friday, December 5, 2025, 5:00 PM
This final AEP is due on Friday Dec. 5th.  Since this is the last day of classes, this is a *hard* deadline -- I will not accept late submissions.

Assignment icon
Homework #12Assignment
Opened: Wednesday, November 19, 2025, 12:00 AM
Due: Wednesday, November 26, 2025, 5:00 PM
Do problems #2, 6, 7, 9 from section 8.5.  Write a short homework report telling me

Which problems were you able to complete?  
What difficulties did you encounter in doing these problems?  What strategies were you able to use to help resolve your questions?
What questions do you have after doing this assignment?
Hand in this report and a solution to #7 by Wednesday, Nov. 26. 
November 24 - November 30
Week Thirteen
Monday:  Continued working on Activity 8.6.2.

Wednesday:  Bonus day!  Today we looked at the Harmonic Series ∑∞𝑛=11𝑛
 and how it comes in the context of a problem involving stacking blocks.  If you weren't in class, here's a short summary of the problem: 
https://mathworld.wolfram.com/BookStackingProblem.html
December 1 - December 7
Week Fourteen
Monday:  Today we went over the Lagrange Error Bound for 𝑇𝑛(𝑥)
 from section 8.6.3 and started Activity 8.6.3.

Wednesday:  We continued working on Activity 8.6.3.

Thursday:  check-in on Taylor series (specifically the material from section 8.5).

Friday:  Zine gallery 