---
title: "Student Support"
format:
  html:
    number-sections: false
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

Whether it's working on homework problems, making quiz corrections, or just reviewing class notes, I expect that much of your learning in this course will happen outside of class. You will have questions from time-to-time and you might not want to wait until our next class to get them answered. Keep in mind that mathematics is a cumulative subject where content builds upon prior knowledge; once you get behind it can be very hard to catch up.

For all of these reasons, it's important that you know how to get your questions answered outside of class. Below you'll find a list of some of the primary ways to get help, but please know that one of my top priorities is to support your learning so if you find you need any additional help accessing support **for any reason** please let me know!

## Drop-In Hours

I have set aside the times listed below during which I am available for drop-in help. You do not need to let me know you're coming -- just stop by my office (BC 270). Many students find these drop-in hours can be particularly helpful if you are working together with classmates. You can work together at one of the tables down the hall from my office and just pop in when you have any questions.

-   Mon, Wed 9:30 - 11
-   Tuesday 1-3 (starting 9/2)

::: callout-note
I'm writing this the week before classes begin. If my schedule changes for some reason, I may need to adjust these times. If that happens, I will let you know!
:::

## Sign-Up Hours

I recognize that your schedule might not allow you to stop by during the posted drop-in hours. Or you simply might find it more convenient to meet with me at a different time. If you go to my [Calendly scheduler](https://calendly.com/hallstro), you can sign-up for a time slot to meet, either in person or via zoom. If there is a specific time that you would like to meet and you don't see it available on the Calendly scheduler, please reach out to me via email!

## Open Door

I have the scheduled drop-in hours simply to give you some specific times when you know that I'll be available -- but you are **always** welcome to stop by my office **at any time**. Unless I'm in class or in a meeting, I will generally be available to meet with you.

## Math Resource Center

The MRC offers both drop-in tutoring as well as scheduled, individualized help. I will post the MRC schedule on Moodle as soon as it becomes available (usually the second week of the semester).
